#include "noise.compute"
#pragma kernel CSMain

RWStructuredBuffer<float> GridOne;
RWStructuredBuffer<float> GridTwo;

float gridSize;

int CoordToIndex(int x, int y, int z)
{
    return gridSize * gridSize * x + gridSize * y + z;
}


[numthreads(4,4,4)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float3 scaled = float3(id.x / 500., id.y / 500., id.z / 500.);
    GridOne[id.x] = snoise(scaled);
}
